### ISSUE TITLE
Can't load Material UI plugin

### ISSUE THREAD

**Issue by hoshinokiseki** [Sevii77/ffxiv_materialui_accent#87]
```
2022-08-28 13:50:15.220 +08:00 [INF] [LOCALPLUGIN] Loading MaterialUI.dll
2022-08-28 13:50:15.225 +08:00 [INF] [LOCALPLUGIN] Finished loading MaterialUI.dll
2022-08-28 13:50:15.305 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOC0yOFQxMzo1MDoxNS4zMDU4MTg2KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5BZ2dyZWdhdGVFeGNlcHRpb246IEEgVGFzaydzIGV4Y2VwdGlvbihzKSB3ZXJlIG5vdCBvYnNlcnZlZCBlaXRoZXIgYnkgV2FpdGluZyBvbiB0aGUgVGFzayBvciBhY2Nlc3NpbmcgaXRzIEV4Y2VwdGlvbiBwcm9wZXJ0eS4gQXMgYSByZXN1bHQsIHRoZSB1bm9ic2VydmVkIGV4Y2VwdGlvbiB3YXMgcmV0aHJvd24gYnkgdGhlIGZpbmFsaXplciB0aHJlYWQuIChNZXRob2Qgbm90IGZvdW5kOiAnU3lzdGVtLklPLkZpbGVJbmZvIERhbGFtdWQuUGx1Z2luLkRhbGFtdWRQbHVnaW5JbnRlcmZhY2UuZ2V0X0NvbmZpZ0ZpbGUoKScuKVxyXG4gLS0tPiBTeXN0ZW0uTWlzc2luZ01ldGhvZEV4Y2VwdGlvbjogTWV0aG9kIG5vdCBmb3VuZDogJ1N5c3RlbS5JTy5GaWxlSW5mbyBEYWxhbXVkLlBsdWdpbi5EYWxhbXVkUGx1Z2luSW50ZXJmYWNlLmdldF9Db25maWdGaWxlKCknLlxyXG4gICBhdCBNYXRlcmlhbFVJLk1hdGVyaWFsVUkuQ2hlY2tQZW51bWJyYSgpXHJcbiAgIGF0IE1hdGVyaWFsVUkuTWF0ZXJpYWxVSS48LmN0b3I+Yl9fMjdfMCgpIGluIEM6XFxzaGhcXHBsdWdpbnNcXGZmeGl2X21hdGVyaWFsdWlfYWNjZW50XFxwbHVnaW5cXE1hdGVyaWFsVUkuY3M6bGluZSAzOFxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS0iLCJDb250ZXh0IjoiVW5vYnNlcnZlZCBleGNlcHRpb24gaW4gVGFzay4ifQ==
2022-08-28 13:50:15.305 +08:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Method not found: 'System.IO.FileInfo Dalamud.Plugin.DalamudPluginInterface.get_ConfigFile()'.)
 ---> System.MissingMethodException: Method not found: 'System.IO.FileInfo Dalamud.Plugin.DalamudPluginInterface.get_ConfigFile()'.
   at MaterialUI.MaterialUI.CheckPenumbra()
   at MaterialUI.MaterialUI.<.ctor>b__27_0() in C:\shh\plugins\ffxiv_materialui_accent\plugin\MaterialUI.cs:line 38
   --- End of inner exception stack trace ---
2022-08-28 13:50:16.454 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOC0yOFQxMzo1MDoxNi40NTQ3NjE0KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5NaXNzaW5nTWV0aG9kRXhjZXB0aW9uOiBNZXRob2Qgbm90IGZvdW5kOiAnU3lzdGVtLklPLkZpbGVJbmZvIERhbGFtdWQuUGx1Z2luLkRhbGFtdWRQbHVnaW5JbnRlcmZhY2UuZ2V0X0NvbmZpZ0ZpbGUoKScuXHJcbiAgIGF0IE1hdGVyaWFsVUkuTWF0ZXJpYWxVSS5DaGVja1BlbnVtYnJhKClcclxuICAgYXQgTWF0ZXJpYWxVSS5VSS5EcmF3U2V0dGluZ3MoKSBpbiBDOlxcc2hoXFxwbHVnaW5zXFxmZnhpdl9tYXRlcmlhbHVpX2FjY2VudFxccGx1Z2luXFxVSS5jczpsaW5lIDk5XHJcbiAgIGF0IE1hdGVyaWFsVUkuVUkuRHJhdygpIGluIEM6XFxzaGhcXHBsdWdpbnNcXGZmeGl2X21hdGVyaWFsdWlfYWNjZW50XFxwbHVnaW5cXFVJLmNzOmxpbmUgNjlcclxuICAgYXQgRGFsYW11ZC5JbnRlcmZhY2UuVWlCdWlsZGVyLk9uRHJhdygpIiwiQ29udGV4dCI6IltcIk1hdGVyaWFsVUlcIl0gVWlCdWlsZGVyIE9uQnVpbGRVaSBjYXVnaHQgZXhjZXB0aW9uIn0=
2022-08-28 13:50:16.454 +08:00 [ERR] [MaterialUI] UiBuilder OnBuildUi caught exception
System.MissingMethodException: Method not found: 'System.IO.FileInfo Dalamud.Plugin.DalamudPluginInterface.get_ConfigFile()'.
   at MaterialUI.MaterialUI.CheckPenumbra()
   at MaterialUI.UI.DrawSettings() in C:\shh\plugins\ffxiv_materialui_accent\plugin\UI.cs:line 99
   at MaterialUI.UI.Draw() in C:\shh\plugins\ffxiv_materialui_accent\plugin\UI.cs:line 69
   at Dalamud.Interface.UiBuilder.OnDraw()
2022-08-28 13:50:18.255 +08:00 [INF] [LOCALPLUGIN] Unloading MaterialUI.dll
2022-08-28 13:50:18.770 +08:00 [INF] [LOCALPLUGIN] Finished unloading MaterialUI.dll
```

**Comment by Sevii77** [comment]
Seems to be caused by either a outdated or modified dalamud version, as it is missing features.
