### ISSUE TITLE
Error on startup with latest update

### ISSUE THREAD

**Issue by Cellane** [Sevii77/ffxiv_materialui_accent#92]
With the latest update, the Material UI skin is no longer applied to the UI, and when I open the configuration window and hit `Apply`, I get the following error after a few moments:

```
Failed writing texture base/ui/uld/harpoonwindowa_selected_v
Index was outside the bounds of the array.

Try a Integrity Check in the Advanced tab
```

Running the Integrity Check reveals no issue, neither does Rediscovering Mods in Penumbra help. Reinstalling of the plug-in has no effect either.

**Comment by Sophie-moonway** [comment]
I have the same problem when starting
![M UI Bug](https://github.com/Sevii77/ffxiv_materialui_accent/assets/121527182/078f2152-015b-41e4-a1f0-ceb9ed95ad5e)

```
12:53:06.123 | ERR [MaterialUI] Failed writing textures
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MaterialUI.Tex.Overlay(Tex overlay) in C:\shh\plugins\ffxiv_materialui_accent\plugin\Tex.cs:line 138
   at MaterialUI.Updater.<Apply>g__walkDirAccent|31_2(Dir dir, String fullPath, String modid, <>c__DisplayClass31_0&) in C:\shh\plugins\ffxiv_materialui_accent\plugin\Updater.cs:line 727
   at MaterialUI.Updater.<Apply>g__walkDirAccent|31_2(Dir dir, String fullPath, String modid, <>c__DisplayClass31_0&) in C:\shh\plugins\ffxiv_materialui_accent\plugin\Updater.cs:line 764
   at MaterialUI.Updater.<Apply>g__walkDirAccent|31_2(Dir dir, String fullPath, String modid, <>c__DisplayClass31_0&) in C:\shh\plugins\ffxiv_materialui_accent\plugin\Updater.cs:line 764
   at MaterialUI.Updater.<Apply>g__walkDirAccent|31_2(Dir dir, String fullPath, String modid, <>c__DisplayClass31_0&) in C:\shh\plugins\ffxiv_materialui_accent\plugin\Updater.cs:line 764
   at MaterialUI.Updater.Apply() in C:\shh\plugins\ffxiv_materialui_accent\plugin\Updater.cs:line 790
12:53:17.246 | INF [LOCALPLUGIN] Finished loading InventorySearchBar.dll
```

**Comment by Cellane** [comment]
Disabling mods in Mod Browser nor deleting the entire `%AppData%/Dalamud/pluginConfigs/MaterialUI` folder (to force redownload) didn't help either.

**Comment by Daccura** [comment]
Can confirm I have the same issue, doesn't work anymore at all.

**Comment by kajoken** [comment]
Got the same problem after the Game crashed right now. 
Integrity Check shows no errors.

**Comment by Cellane** [comment]
Thanks for the super-quick fix! Gonna try now ❤️

**Comment by Daccura** [comment]
Ty for the fast fix, working now!

**Comment by kajoken** [comment]
Working for me as well but I had to do a clean reinstall from scratch, else it would still give the same error.
